import type { GetServerSidePropsContext } from "next";
import Head from "next/head";
import Image from "next/image";
import type Friend from "@/interfaces/friend.interface";

interface HomeProps {
  friends: Friend[];
}

const Home = ({ friends }: HomeProps) => {
  return (
    <div>
      <Head>
        <title>Next.js SSR - Data Fetching</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-start items-center h-screen p-20 bg-slate-200">
        <section className="h-1/3">
          <h1 className="text-5xl font-medium">
            Welcome{" "}
            <span className="text-blue-600 hover:text-blue-500 underline decoration-wavy">
              Friends
            </span>
            !
          </h1>
        </section>
        <section className="h-full my-8">
          <ul className="flex flex-wrap gap-8 justify-start items-center h-full">
            {friends.map((friend: Friend) => (
              <li
                className="flex flex-col items-center"
                key={friend.email + friend.lastName}
              >
                <div className="flex justify-center items-center align-middle rounded-full hover:shadow-md hover:bg-red-200 p-2">
                  <Image
                    className="rounded-full"
                    src={friend.avatar}
                    alt={friend.name}
                    height={100}
                    width={100}
                  />
                </div>

                <h2 className="text-xl font-medium my-2">{friend.name}</h2>
              </li>
            ))}
          </ul>
        </section>
        <footer className="h-1/3 flex justify-center gap-6 text-2xl text-blue-600">
          <a className="hover:text-blue-500" href="https://twitter.com/trun222">
            Twitter
          </a>
          <a className="hover:text-blue-500" href="https://jtosdev.com/">
            JtoSDev.com
          </a>
          <a
            className="hover:text-blue-500"
            href="https://thomasunderwoodii.medium.com/"
          >
            Medium
          </a>
        </footer>
      </main>
    </div>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const data = await fetch("http://localhost:3000/api/friends").then(
    (response) => response.json()
  );

  return {
    props: {
      friends: data?.friends,
    },
  };
}

export default Home;
